### ISSUE TITLE
Library is broken.

### ISSUE THREAD

**Issue by sulaiman1073** [benrei/joi-to-openapi-definition#2]
I've ran the example in the readme, and got this:
```bash
assert.js:374
    throw err;
    ^

AssertionError [ERR_ASSERTION]: requires a joi schema object
    at convert (/home/***/test/node_modules/joi-to-json-schema/build/index.js:235:24)
    at Object.add_joi_model (/home/***/test/node_modules/joi-to-openapi-definition/index.js:11:19)
    at Object.<anonymous> (/home/***/test/index.js:33:6)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
```
Using these versions
```json
  "dependencies": {
    "@hapi/joi": "^17.1.1",
    "joi-to-openapi-definition": "^0.1.1"
  }
```

**Comment by benrei** [comment]
Hi,
I'm waiting on a update from the 'joi-to-json-schema' package to support '@hapi/joi": "^17.1.1'.
Currently only @hapi/joi up to 15.x is supported.
[This issue](https://github.com/benrei/joi-to-openapi-definition/issues/1) is related as well
